### PR TITLE
Msvc fixes

### PR DESCRIPTION
**Pull request by cmbrandenburg**
This branch fixes several problems, all of which I encountered getting the library up-and-running as a DLL using Visual Studio. One of those problems was Issue #48, so there's a fix for that in this pull request.

This pull request also includes a fix for a couple of mischievous `#include` statements that made it hard to run an automatic amalgamator on the URI library.

The other fixes should be clear. One change is converting the `dllexport` declaration from per-class to per-function. This eliminates compiler warnings when building or using the library. Apparently it's not a good idea to mix per-class `dllexport` declarations with classes that contain STL members, such as `std::string`.

### CODE REVIEW

**Comment by glynos** [comment]
Hi Craig,

Thanks for doing this. But I have a question: you say that it's not a good idea to mix per-class dllexport declarations with classes that contain STL members. Do you have a link to something that explains this? It's interesting you say it because I have usually have seen the dllexport declarations made per-class. I'm not normally a Windows programming guy, so I don't fully know all the subtleties.

**Comment by cmbrandenburg** [comment]
I reverted the per-member `dllexport` declarations to be per-class again. This follows the [Boost guidelines](http://www.boost.org/development/separate_compilation.html), where the key is disabling compiler warnings with `#pragma`.

The resulting pull request has gotten a tad messy, what with all the commits, some undoing others. You may want to squash the merge.

**Comment by glynos** [comment]
I am happy with the changes as they are. Many thanks for your contribution!

**Comment by cmbrandenburg** [comment]
Thank you for making this library!

**Pull request merged**
